RUN_ENV: dev
LOG_PATH: "/var/log"
LOG_FILENAME: "gin_demo.log"

APP_ID: ""
APP_SECRET: ""
TOKEN: ""
AES_KEY: ""

REDIS_HOST: localhost
REDIS_PORT: "6379"
REDIS_PASS: "123456"
REDIS_DB: "0"

WEWORK_TOKEN: ""
WEWORK_RECV_ID: ""
WEWORK_ENCODE_AES_KEY: ""